### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by zaitsevid** [microsoftgraph/nodejs-connect-sample#3]
Cloned to desktop, made all preparations in readme.
Trying to login, msonline login screen succeeds and returns code to /token. Then nothing happens, no errors. Browser shows the same "Connect to Microsoft Graph" button.

**Comment by lovat** [comment]
We are having the same issue as @ZayaPro

**Comment by mFarghaly** [comment]
The same issue, nothing works !

**Comment by pme123** [comment]
Same problem here

**Comment by bitschmidty** [comment]
Same.

It seems that under the hood the passport.authenticate call in the /token route is coming back '401 unauthorized'.

**Comment by jasonjoh** [comment]
Hi everyone. Sorry for the delay in responding here. The folks who were maintaining this sample have moved on to other roles and this repo sort of fell through the cracks :(. I'm taking a look at it today and will update shortly.

**Comment by jasonjoh** [comment]
Ok, well the good news (?) is that I reproduce this. I'll dig further into what's happening. Thanks @pinacodelada for the added detail!

**Comment by jasonjoh** [comment]
Folks, I think I found the issue and squashed it. See the notes in the pull request for more info.

I'm opening another issue to track updating the Graph library to the latest version and to fix the "undefined" value that shows up in the email text box after you login.
